'use client'
// import type { Metadata } from "next";
import localFont from "next/font/local";
import { Provider } from "@/components/ui/provider"
import { ChakraProvider } from "@chakra-ui/react/styled-system";
import customTheme from "@/styles/theme";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <ChakraProvider value={customTheme}>
            <Provider>{children}</Provider>
        </ChakraProvider> 
      </body>
    </html>
  );
}
